### ISSUE TITLE
Screen will not rotate

### ISSUE THREAD

**Issue by x02839** [JDCTeam/issue_tracking_cm13#4]
Phone model: ex. jfltexx or SM-975L
Baseband version: S975LUDUANB1
ROM version: OptimizedCM-13-20160606
GApps Package: 
open_gapps-arm-6.0-pico-20160703

Screen will not rotate in any app.

**Comment by LukasMRam** [comment]
I have the same problem, I can not rotate the screen in any application unless you restart the phone, but that does not last more than 3 minutes and the problem returns.

**Comment by didou038** [comment]
Hi, same problem for me.

**Comment by B--B** [comment]
https://github.com/AOSP-JF-MM/proprietary_vendor_samsung/commit/5d186deedd562ff65a095a2e3ca737ea2b02fdee I'm at work and I don't have time to find opt cm link, replace that library, change permissions, reboot and you are fine again

**Comment by dkati** [comment]
We have already fixed that issue people. Please use an updated version of rom :)

**Comment by didou038** [comment]
I use this version : OptimizedCm-13-20160606 isn't it the last ?

**Comment by x02839** [comment]
Nope

James

**Comment by x02839** [comment]
https://www.androidfilehost.com/?w=files&flid=74669

**Comment by didou038** [comment]
Thank you and sorry !

**Comment by x02839** [comment]
No worries. One team, one dream right?

**Comment by didou038** [comment]
It's the first time I use a rom and I'm discovering this and the community ! Wonderful !

**Comment by dkati** [comment]
No problem mate :)

**Comment by x02839** [comment]
Any word on a fix for the screen not waking up?

**Comment by dkati** [comment]
We have discussed it again that issue. U can use our roms with cm nightly kernel mate, until  we fix it :)

**Comment by x02839** [comment]
My apologies,  I must have missed that post. I appreciate all the time and
energy you dedicate. Thanks again

James
