### ISSUE TITLE
shutdown is too slow

### ISSUE THREAD

**Issue by akremche** [JDCTeam/issue_tracking_cm13#6]
Phone model: ex. jfltexx or GT-I9505
Baseband version: ex. I9505XXUHOD7
ROM version: ex. 20160116
GApps Package: CM GApps [date] or Open GApps [type] [date] or Slim GApps [type] [date] ex. Open GApps Micro 20160116

Did you do a clean install for the currently installed build? yes

Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no
(Superuser related issues only) Did you install SuperSU? no

**Comment by dkati** [comment]
hey mate.you are using a very old version...

**Comment by akremche** [comment]
Hello,
![screenshot_20160828-060357](https://cloud.githubusercontent.com/assets/11713891/18031717/c817ad44-6ced-11e6-85f9-d5caeb6830a3.png)

ah sorry, did not put version, but i m using the OptimizedCM-13-20160806-jflte-Aroma-STABLE2
thank you.

**Comment by dkati** [comment]
what exactly shutdown is slow means :/ ? how slow
